### ISSUE TITLE
Changing shape's position doesn't work

### ISSUE THREAD

**Issue by niedzadr** [MineGame159/BeefSFML#1]
Hi, Beef newbie here. I'm comming form C++ and wanted to check out Beef and maybe port my project.
I followed QuickStart's instructions and stumbled upon an issue when trying to move a RectangleShape:

```
using (let window = new RenderWindow(VideoMode(800, 600), "Game")) {

	window.ClosedEvent.Add(scope (window) => {
		window.Close();
	});

	RectangleShape shape = scope RectangleShape(Vector2f(30.0f, 50.0f));
	shape.FillColor = Color.Red;
	shape.Transform.Position = Vector2f(300, 300);

	window.MouseMovedEvent.Add(scope (window, data) => {
		shape.Transform.Position = Vector2f(data.X, data.Y);
	});
	
	RenderStates states = RenderStates(BlendMode.None, null, null, Matrix3x3.Identity);

	while (window.IsOpen()) {
		window.DispatchEvents();
		window.Clear(Color.CornflowerBlue);
		window.Draw(shape, states);
		window.Display();
	}
}
```

Shape's position doesn't get changed at all. Not when I first set it, nor when I want it to follow the mouse movements

**Comment by EnokViking** [comment]
Hi!
You're passing the identity matrix to RenderStates instead of the transformation matrix, which is available through the Transform2D.GetMatrix method.

**Comment by niedzadr** [comment]
Thanks, that works! I just assumed it will work 1 to 1 like C++ version where the transform of the object is combined with transform passed to RenderStates.

**Comment by EnokViking** [comment]
In SFML, sf::Transform is a 3x3 matrix, but I decided to name it Matrix3x3 and add a new type which abstracts the matrix transformations instead, namely Transform2D, simply because I thought it made more sense. In hindsight it's probably just a source of confusion if you're already familiar with SFML.
